import { useNavigate } from "react-router-dom";
import CreateBotProgress from "../components/CreateBotProgress.jsx";
import { useCreateBot } from "../context/CreateBotContext.jsx";

export default function CreateBotSetup() {
  const navigate = useNavigate();
  const { category, items, updateItem, addItem, removeItem, contacts, setContact, features, templates, description, businessName, setField, greeting, botId } = useCreateBot();
  const label = category === "shop" ? "Товары" : category === "cafe" ? "Позиции меню" : "Услуги";
  return <div><CreateBotProgress /><div className="grid max-w-5xl gap-6 lg:grid-cols-[1.1fr_.9fr]">
    <section className="rounded-2xl bg-white p-7 shadow-sm sm:p-9"><h1 className="font-display text-2xl font-bold text-navy-950">Содержание бота</h1><p className="mt-2 text-sm text-gray-500">Добавьте товары, услуги и контакты. Валюта — тенге (₸).</p>
      <div className="mt-6"><h2 className="text-sm font-semibold text-navy-950">{label}</h2><p className="mt-1 text-xs leading-5 text-amber-700">Шаблонные товары и цены — примеры. Перед запуском замени или удали их, чтобы клиенты видели только актуальный каталог.</p><div className="mt-2 divide-y divide-gray-100 rounded-xl border border-gray-100 px-4">{items.map((item, index) => <div key={index} className="flex items-center gap-2 py-3"><input aria-label={`${label}: название`} value={item.name} onChange={(event) => updateItem(index, "name", event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" /><input aria-label="Цена в тенге" type="number" min="0" value={item.price} onChange={(event) => updateItem(index, "price", Number(event.target.value))} className="w-24 bg-transparent text-right text-sm outline-none" /><span className="text-sm text-gray-400">₸</span><button type="button" aria-label="Удалить позицию" onClick={() => removeItem(index)} className="rounded px-2 text-lg text-red-500 hover:bg-red-50">×</button></div>)}</div><button onClick={addItem} className="mt-3 text-sm font-medium text-accent-600 hover:underline">+ Добавить позицию</button></div>
      <div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Название бизнеса" value={businessName} onChange={(value) => setField("businessName", value)} placeholder="Например, «Север»" /><Field label="График работы" value={contacts.hours} onChange={(value) => setContact("hours", value)} placeholder="Ежедневно, 10:00–20:00" /><Field label="Адрес и город" value={contacts.address} onChange={(value) => setContact("address", value)} placeholder="Алматы, улица Абая, 10" /><Field label="Телефон для связи" value={contacts.phone} onChange={(value) => setContact("phone", value)} placeholder="+7 7XX XXX XX XX" /><Field label="Язык общения" value={contacts.language} onChange={(value) => setContact("language", value)} placeholder="Русский и казахский" /></div>
      <label className="mt-5 block"><span className="mb-2 block text-sm font-semibold text-navy-950">Приветствие</span><textarea rows={3} value={greeting} onChange={(event) => setField("greeting", event.target.value)} className="w-full resize-y rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm leading-6 outline-none focus:border-accent-500" /></label>
      <div className="mt-7 flex justify-between"><button onClick={() => navigate("/create/structure")} className="rounded-xl border border-gray-200 px-5 py-2.5 text-sm font-semibold text-navy-950 hover:bg-gray-50">Назад</button><button onClick={() => navigate("/create/launch")} className="rounded-xl bg-navy-950 px-5 py-2.5 text-sm font-semibold text-white hover:bg-navy-900">Проверить и продолжить →</button></div>
    </section>
    <aside className="h-fit rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-navy-950">Предпросмотр бота</p><p className="mt-1 text-xs text-gray-400">Так будут выглядеть первые сообщения</p><div className="mt-5 rounded-2xl bg-[#e8f1f6] p-4"><div className="max-w-[90%] rounded-xl rounded-tl-none bg-white p-3 text-sm leading-5 text-navy-950">{greeting}</div><div className="mt-2 rounded-xl rounded-tl-none bg-white p-3 text-xs leading-5 text-gray-600">{features.join(" · ")}</div></div><p className="mt-5 text-xs font-semibold text-navy-950">{templates[category]?.emoji} {templates[category]?.label}</p><p className="mt-2 text-xs leading-5 text-gray-500">{description}</p><p className="mt-5 rounded-lg bg-blue-50 p-3 text-xs leading-5 text-blue-800">{botId ? "Токен уже зашифрован и сохранён локальным сервером." : "Сначала подключи токен бота."}</p></aside>
  </div></div>;
}

function Field({ label, value, onChange, placeholder }) { return <label className="block"><span className="mb-1.5 block text-xs font-medium text-gray-500">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm outline-none focus:border-accent-500" /></label>; }
