import { useEffect, useState } from "react";
import { apiFetch } from "../lib/api.js";

export default function Settings() {
  const [health, setHealth] = useState(null);
  useEffect(() => { apiFetch("/api/health").then((response) => response.json()).then(setHealth).catch(() => setHealth({ ok: false })); }, []);
  return <div className="max-w-4xl"><p className="mb-4 text-sm text-gray-400">Рабочее пространство / <span className="text-gray-600">Настройки</span></p><div className="rounded-2xl bg-white p-7 shadow-sm sm:p-9"><h1 className="font-display text-2xl font-bold text-navy-950">Службы платформы</h1><p className="mt-2 text-sm leading-6 text-gray-500">Пользователю нужен только аккаунт и браузер. Telegram-сценарии выполняет сервер платформы, а данные аккаунтов и ботов хранятся в Supabase.</p><section className="mt-7 border-t border-gray-100 pt-6"><h2 className="text-sm font-semibold text-navy-950">Состояние</h2><dl className="mt-4 space-y-3 text-sm"><Row label="API сервера" value={health?.ok ? "Доступен" : health ? "Не отвечает" : "Проверяем…"} /><Row label="Supabase" value={health?.supabase ? "Настроен" : "Не настроен на сервере"} /><Row label="ИИ конструктора" value={health?.ai ? `${health.model} · доступна серверу` : "Не настроен на сервере"} /><Row label="Лимит ИИ" value={health ? `${health.limit} генераций в месяц на аккаунт` : "—"} /></dl></section><section className="mt-7 border-t border-gray-100 pt-6"><h2 className="text-sm font-semibold text-navy-950">Защита токена Telegram</h2><p className="mt-2 text-xs leading-5 text-gray-500">Токен шифруется AES-256-GCM перед записью в Supabase. Ключ шифрования задан только в переменных окружения сервера и не передаётся браузеру. Столбец токена закрыт для клиентских ролей.</p></section><section className="mt-7 border-t border-gray-100 pt-6"><h2 className="text-sm font-semibold text-navy-950">Первичная настройка</h2><ol className="mt-3 list-inside list-decimal space-y-2 text-xs leading-5 text-gray-500"><li>В Supabase Dashboard откройте SQL Editor и выполните файл supabase/schema.sql.</li><li>На сервере платформы задайте SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, SUPABASE_SECRET_KEY и BOT_TOKEN_ENCRYPTION_KEY.</li><li>Настройте серверный серверную модель ИИ и постоянный Node.js runner для Telegram polling.</li></ol></section><section className="mt-7 border-t border-gray-100 pt-6"><h2 className="text-sm font-semibold text-navy-950">Черновик конструктора</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-gray-500">Описание и временный черновик сохраняются в этом браузере; опубликованные боты и аккаунты — в Supabase.</p><button onClick={() => { localStorage.removeItem("bots-kz-workspace-v1"); window.location.reload(); }} className="mt-4 rounded-lg border border-gray-200 px-4 py-2 text-sm font-semibold text-red-600 hover:bg-red-50">Удалить черновик из браузера</button></section></div></div>;
}

function Row({ label, value }) { return <div className="flex flex-col justify-between gap-1 sm:flex-row"><dt className="text-gray-500">{label}</dt><dd className="font-medium text-navy-950">{value}</dd></div>; }
